config/routes.rb
Rails.application.routes.draw do

  resources (:schools) {resources :units}
  resources (:schools) {resources :students}
  
  devise_for :logins
  resources :payment_data
  resources :invoices
  resources :product_custumers
  #resources :students
  #resources :units
  resources :employees
  resources :customers
  resources :teachers
  resources :logins
  resources :users
  resources :school_histories
  resources :permissions
  resources :type_users
  resources :schools
  resources :school_years
  resources :matters
  resources :classrooms
  get 'notification/create'

  root to: 'home#index'
  
  get 'order/new'

  post 'order/create'

  get 'order/index'

  resources :products

  post 'notification', to: 'notification#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :unit, required: false
  belongs_to :city, required: false




  # Coloquei todos os campos do endereço dentro dessa de Address
  # Campos colocados: CEP, Street, Number, District, Complement, City, State

end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :addresses
end

app/models/classroom.rb
class Classroom < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :address
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :city
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/filiation.rb
class Filiation < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
  # Nota
  belongs_to :student
  belongs_to :matter_school_year
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :product_custumer
  belongs_to :school
end

app/models/login.rb
class Login < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user
end

app/models/matter.rb
class Matter < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :unit
  belongs_to :type_payment
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
end

app/models/school.rb
class School < ApplicationRecord
  has_many :students
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school, required: false
  belongs_to :customer, required: false
  belongs_to :school_history, required: false

  has_one :student_user
  has_one :user, :through => :student_user

  has_many :studant_matters
  has_many :grades
  has_many :attendances

  accepts_nested_attributes_for :student_user
  #accepts_nested_attributes_for :user

  #
  # Falta:
  # Product customer
  # Student User
  # Filliation Student
  #

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :school
  has_one :address
  has_one :contact_phone
  has_one :contact_email

  accepts_nested_attributes_for :address, :contact_phone

  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :type_user, required: false
  belongs_to :unit, required: false
  belongs_to :login, required: false
  belongs_to :student, required: false
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:registration, :active, :user_id)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :registration %>
    <%= form.text_field :registration, id: :teacher_registration %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.number_field :active, id: :teacher_active %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :teacher_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professores</h1>

<table>
  <thead>
    <tr>
      <th>Matrícula</th>
      <th>Ativo</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.registration %></td>
        <td><%= teacher.active %></td>
        <td><%= teacher.user %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo professor', new_teacher_path, :class => 'btn btn-primary' %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Registration:</strong>
  <%= @teacher.registration %>
</p>

<p>
  <strong>Active:</strong>
  <%= @teacher.active %>
</p>

<p>
  <strong>User:</strong>
  <%= @teacher.user %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>