config/routes.rb
Rails.application.routes.draw do

  resources (:schools) {resources :units}
  resources (:schools) {resources :students}
  
  devise_for :logins
  resources :payment_data
  resources :invoices
  resources :product_custumers
  #resources :students
  #resources :units
  resources :employees
  resources :customers
  resources :teachers
  resources :logins
  resources :users
  resources :school_histories
  resources :permissions
  resources :type_users
  resources :schools
  resources :school_years
  resources :matters
  resources :classrooms
  get 'notification/create'

  root to: 'home#index'
  
  get 'order/new'

  post 'order/create'

  get 'order/index'

  resources :products

  post 'notification', to: 'notification#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :unit, required: false
  belongs_to :city, required: false




  # Coloquei todos os campos do endereço dentro dessa de Address
  # Campos colocados: CEP, Street, Number, District, Complement, City, State

end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :addresses
end

app/models/classroom.rb
class Classroom < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :address
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :city
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/filiation.rb
class Filiation < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
  # Nota
  belongs_to :student
  belongs_to :matter_school_year
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :product_custumer
  belongs_to :school
end

app/models/login.rb
class Login < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user
end

app/models/matter.rb
class Matter < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :unit
  belongs_to :type_payment
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
end

app/models/school.rb
class School < ApplicationRecord
  has_many :students
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school, required: false
  belongs_to :customer, required: false
  belongs_to :school_history, required: false

  has_one :student_user
  has_one :user, :through => :student_user

  has_many :studant_matters
  has_many :grades
  has_many :attendances

  accepts_nested_attributes_for :student_user
  #accepts_nested_attributes_for :user

  #
  # Falta:
  # Product customer
  # Student User
  # Filliation Student
  #

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :school
  has_one :address
  has_one :contact_phone
  has_one :contact_email

  accepts_nested_attributes_for :address, :contact_phone

  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :type_user, required: false
  belongs_to :unit, required: false
  belongs_to :login, required: false
  belongs_to :student, required: false
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :social_name, :cnpj, :active)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :school_name %>
  </div>

  <div class="field">
    <%= form.label :social_name %>
    <%= form.text_field :social_name, id: :school_social_name %>
  </div>

  <div class="field">
    <%= form.label :cnpj %>
    <%= form.text_field :cnpj, id: :school_cnpj %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.number_field :active, id: :school_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Social name</th>
      <th>Cnpj</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.social_name %></td>
        <td><%= school.cnpj %></td>
        <td><%= school.active %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Social name:</strong>
  <%= @school.social_name %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @school.cnpj %>
</p>

<p>
  <strong>Active:</strong>
  <%= @school.active %>
</p>

<%= link_to 'Editar', edit_school_path(@school) %> |
<%= link_to 'Voltar', schools_path %>

<%= link_to 'Nova unidade', new_school_unit_path(@school) %>

<%# new_configuracao_ura_linha_configuracao_path(@configuracao_ura) %>