config/routes.rb
Rails.application.routes.draw do

  resources (:schools) {resources :units}
  resources (:schools) {resources :students}
  
  devise_for :logins
  resources :payment_data
  resources :invoices
  resources :product_custumers
  #resources :students
  #resources :units
  resources :employees
  resources :customers
  resources :teachers
  resources :logins
  resources :users
  resources :school_histories
  resources :permissions
  resources :type_users
  resources :schools
  resources :school_years
  resources :matters
  resources :classrooms
  get 'notification/create'

  root to: 'home#index'
  
  get 'order/new'

  post 'order/create'

  get 'order/index'

  resources :products

  post 'notification', to: 'notification#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :unit, required: false
  belongs_to :city, required: false




  # Coloquei todos os campos do endereço dentro dessa de Address
  # Campos colocados: CEP, Street, Number, District, Complement, City, State

end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :addresses
end

app/models/classroom.rb
class Classroom < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :address
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :city
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
  # Nota
  belongs_to :student
  belongs_to :matter_school_year
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :product_custumer
  belongs_to :school
end

app/models/login.rb
class Login < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user
end

app/models/matter.rb
class Matter < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :unit
  belongs_to :type_payment
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
end

app/models/school.rb
class School < ApplicationRecord
  has_many :students
end

app/models/school_history.rb
class SchoolHistory < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school, required: false
  belongs_to :customer, required: false
  belongs_to :school_history, required: false

  has_one :student_user
  has_one :user, :through => :student_user

  has_many :studant_matters
  has_many :grades
  has_many :attendances

  accepts_nested_attributes_for :student_user
  #accepts_nested_attributes_for :user

  #
  # Falta:
  # Product customer
  # Student User
  # Filliation Student
  #

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :school
  has_one :address
  has_one :contact_phone
  has_one :contact_email

  accepts_nested_attributes_for :address, :contact_phone

  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :type_user, required: false
  belongs_to :unit, required: false
  belongs_to :login, required: false
  belongs_to :student, required: false
end

app/controllers/school_histories_controller.rb
class SchoolHistoriesController < ApplicationController
  before_action :set_school_history, only: [:show, :edit, :update, :destroy]

  # GET /school_histories
  # GET /school_histories.json
  def index
    @school_histories = SchoolHistory.all
  end

  # GET /school_histories/1
  # GET /school_histories/1.json
  def show
  end

  # GET /school_histories/new
  def new
    @school_history = SchoolHistory.new
  end

  # GET /school_histories/1/edit
  def edit
  end

  # POST /school_histories
  # POST /school_histories.json
  def create
    @school_history = SchoolHistory.new(school_history_params)

    respond_to do |format|
      if @school_history.save
        format.html { redirect_to @school_history, notice: 'School history was successfully created.' }
        format.json { render :show, status: :created, location: @school_history }
      else
        format.html { render :new }
        format.json { render json: @school_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /school_histories/1
  # PATCH/PUT /school_histories/1.json
  def update
    respond_to do |format|
      if @school_history.update(school_history_params)
        format.html { redirect_to @school_history, notice: 'School history was successfully updated.' }
        format.json { render :show, status: :ok, location: @school_history }
      else
        format.html { render :edit }
        format.json { render json: @school_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_histories/1
  # DELETE /school_histories/1.json
  def destroy
    @school_history.destroy
    respond_to do |format|
      format.html { redirect_to school_histories_url, notice: 'School history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_history
      @school_history = SchoolHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_history_params
      params.require(:school_history).permit(:birthdate, :naturalness, :nationality, :document_id, :state, :birth_certificate)
    end
end

app/helpers/school_histories_helper.rb
module SchoolHistoriesHelper
end

app/views/school_histories/_form.html.erb
<%= form_with(model: school_history, local: true) do |form| %>
  <% if school_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school_history.errors.count, "error") %> prohibited this school_history from being saved:</h2>

      <ul>
      <% school_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate, id: :school_history_birthdate %>
  </div>

  <div class="field">
    <%= form.label :naturalness %>
    <%= form.text_field :naturalness, id: :school_history_naturalness %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality, id: :school_history_nationality %>
  </div>

  <div class="field">
    <%= form.label :document_id %>
    <%= form.text_field :document_id, id: :school_history_document_id %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :school_history_state %>
  </div>

  <div class="field">
    <%= form.label :birth_certificate %>
    <%= form.text_field :birth_certificate, id: :school_history_birth_certificate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/school_histories/edit.html.erb
<h1>Editing School History</h1>

<%= render 'form', school_history: @school_history %>

<%= link_to 'Show', @school_history %> |
<%= link_to 'Back', school_histories_path %>

app/views/school_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>School Histories</h1>

<table>
  <thead>
    <tr>
      <th>Birthdate</th>
      <th>Naturalness</th>
      <th>Nationality</th>
      <th>Document</th>
      <th>State</th>
      <th>Birth certificate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @school_histories.each do |school_history| %>
      <tr>
        <td><%= school_history.birthdate %></td>
        <td><%= school_history.naturalness %></td>
        <td><%= school_history.nationality %></td>
        <td><%= school_history.document_id %></td>
        <td><%= school_history.state %></td>
        <td><%= school_history.birth_certificate %></td>
        <td><%= link_to 'Show', school_history %></td>
        <td><%= link_to 'Edit', edit_school_history_path(school_history) %></td>
        <td><%= link_to 'Destroy', school_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School History', new_school_history_path %>

app/views/school_histories/new.html.erb
<h1>New School History</h1>

<%= render 'form', school_history: @school_history %>

<%= link_to 'Back', school_histories_path %>

app/views/school_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Birthdate:</strong>
  <%= @school_history.birthdate %>
</p>

<p>
  <strong>Naturalness:</strong>
  <%= @school_history.naturalness %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @school_history.nationality %>
</p>

<p>
  <strong>Document:</strong>
  <%= @school_history.document_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @school_history.state %>
</p>

<p>
  <strong>Birth certificate:</strong>
  <%= @school_history.birth_certificate %>
</p>

<%= link_to 'Edit', edit_school_history_path(@school_history) %> |
<%= link_to 'Back', school_histories_path %>