config/routes.rb
Rails.application.routes.draw do

  resources (:schools) {resources :units}
  resources (:schools) {resources :students}
  
  devise_for :logins
  resources :payment_data
  resources :invoices
  resources :product_custumers
  #resources :students
  #resources :units
  resources :employees
  resources :customers
  resources :teachers
  resources :logins
  resources :users
  resources :school_histories
  resources :permissions
  resources :type_users
  resources :schools
  resources :school_years
  resources :matters
  resources :classrooms
  get 'notification/create'

  root to: 'home#index'
  
  get 'order/new'

  post 'order/create'

  get 'order/index'

  resources :products

  post 'notification', to: 'notification#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :unit, required: false
  belongs_to :city, required: false




  # Coloquei todos os campos do endereço dentro dessa de Address
  # Campos colocados: CEP, Street, Number, District, Complement, City, State

end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :addresses
end

app/models/classroom.rb
class Classroom < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :address
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :city
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/filiation.rb
class Filiation < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
  # Nota
  belongs_to :student
  belongs_to :matter_school_year
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :product_custumer
  belongs_to :school
end

app/models/login.rb
class Login < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user
end

app/models/matter.rb
class Matter < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :unit
  belongs_to :type_payment
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
end

app/models/school.rb
class School < ApplicationRecord
  has_many :students
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school, required: false
  belongs_to :customer, required: false
  belongs_to :school_history, required: false

  has_one :student_user
  has_one :user, :through => :student_user

  has_many :studant_matters
  has_many :grades
  has_many :attendances

  accepts_nested_attributes_for :student_user
  #accepts_nested_attributes_for :user

  #
  # Falta:
  # Product customer
  # Student User
  # Filliation Student
  #

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :school
  has_one :address
  has_one :contact_phone
  has_one :contact_email

  accepts_nested_attributes_for :address, :contact_phone

  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :type_user, required: false
  belongs_to :unit, required: false
  belongs_to :login, required: false
  belongs_to :student, required: false
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @page_header = "Unidades"
    @school = School.find(params[:school_id])
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @page_header = "Detalhe Unidade"
  end

  # GET /units/new
  def new
    @page_header = "Nova Unidade"
    @unit = Unit.new
    @unit.build_address
    @unit.build_contact_phone
    @school = School.find(params[:school_id])
  end

  # GET /units/1/edit
  def edit
    @page_header = "Editar Unidade"
    @school = @unit.school
  end

  # POST /units
  # POST /units.json
  def create
    @school = School.find(params[:school_id])
    @unit = Unit.new(unit_params)
    @units = Unit.where(school_id: @school.id)

    respond_to do |format|
      if @unit.save
        @page_header = "Unidades"
        format.html { redirect_to({action: "index"}, notice: 'Unidade criada com sucesso.' )}
        format.json { render :show, status: :created, location: @unit }
      else
        @page_header = "Nova Unidade"
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    @school = School.find(params[:school_id])
    @units = Unit.where(school_id: @school.id)

    respond_to do |format|
      if @unit.update(unit_params)
        #@unit.contact_phone.save
        format.html { redirect_to({action: "index"}, notice: 'Unidade foi atualizada com sucesso.' )}
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unidade foi apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :active, :school_id, :contact_phone_id, :contact_email_id, address_attributes: [:cep, :street, :number, :district, :complement], contact_phone_attributes: [:phone])
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= simple_form_for([@school, @unit], html: { style: 'width: 35%' }) do |f| %>
  <%= f.input :name, :label => "Nome:" %>
  <%= f.input :active, :as => :hidden, :input_html => {:value => 1}  %>
  <%= f.input :school_id, :as => :hidden, :input_html => {:value => @school.id}  %>
  <%= f.simple_fields_for :address do |a| %>
    <%= a.input :cep %>
    <%= a.input :street, label: "Logradouro:" %>
    <%= a.input :number, label: "Número:" %>
    <%= a.input :district, label: "Bairro:" %>
    <%= a.input :complement, label: "Complemento:"  %>
  <% end %>
  <%= f.simple_fields_for :contact_phone do |p| %>
    <%= p.input :phone, label: "Telefone:" %>
  <% end %>
  <br>
  <% if @unit.id == nil %>
    <%= f.button :submit, "Criar Unidade", :class => "btn btn-success" %>
  <% else %>
    <%= f.button :submit, "Atualizar Unidade", :class => "btn btn-success" %>
  <% end %>
<% end %>

<br>

app/views/units/edit.html.erb
<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', school_units_path(@school) %>

app/views/units/index.html.erb
<table class="table table-striped" >
  <thead>
    <tr>
      <th>Nome</th>
      <th>Situação</th>
      <th>Escola</th>
      <th>endereço</th>
      <th>Telefone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.active %></td>
        <td><%= unit.school.name %></td>
        <td><%= unit.address %></td>
        <% if !unit.contact_phone.nil? %>
        <td><%= unit.contact_phone.phone %></td>
        <% else %>
        <td>Não informado</td>
        <% end %>

        <% if !unit.contact_email.nil? %>
          <td><%= unit.contact_email.email %></td>
        <% else %>
          <td>Não informado</td>
        <% end %>

        <td><%#= link_to 'Detalhes', unit %></td>
        <td><%= link_to 'Editar', edit_school_unit_path(@school.id, unit) %></td>
        <td><%#= link_to 'Apagar', unit, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Unidade', new_school_unit_path(1), :class => "btn btn-primary" %>

<br>
<br>

app/views/units/new.html.erb
<% if flash[:alert] %>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
<% end %>

<%= render 'form', unit: @unit %>

<%= link_to 'Voltar', school_units_path(@school.id) %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @unit.active %>
</p>

<p>
  <strong>School:</strong>
  <%= @unit.school %>
</p>

<p>
  <strong>Address:</strong>
  <%= @unit.address %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @unit.contact_phone %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @unit.contact_email %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>